### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by mike1123412** [mundher/local-global#5]
Dear Mundher, 
I have unpacked the images, put the proper path, but I get the following error:

`Experiment LocalGlobalNetwork
------------ fold 1 ------------
Traceback (most recent call last):
  File "/home/mike/local-global-master/experiments.py", line 200, in <module>
    experiments[exp_name](data_path)
  File "/home/mike/local-global-master/experiments.py", line 74, in expLocalGlobal
    deterministic=True
  File "/home/mike/local-global-master/kflod.py", line 53, in kfold
    trset, testset = dataset_func(path.join(src_path,str(fold)))
  File "/home/mike/local-global-master/preprocessing.py", line 87, in get_dataset
    im = imread(path.join(dir,f'{id:.0f}.{j}.png'))
  File "/home/mike/anaconda3/envs/DeepLung-1-NEW/lib/python3.7/site-packages/imageio/core/functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/mike/anaconda3/envs/DeepLung-1-NEW/lib/python3.7/site-packages/imageio/core/functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/home/mike/anaconda3/envs/DeepLung-1-NEW/lib/python3.7/site-packages/imageio/core/request.py", line 124, in __init__
    self._parse_uri(uri)
  File "/home/mike/anaconda3/envs/DeepLung-1-NEW/lib/python3.7/site-packages/imageio/core/request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: '/home/mike/local-global-master/lidc_img/0/0.0.png`

**Comment by AlejandraM97** [comment]
I get the same error trying to tun this repo... Were you able to find out what the error was?
It's mostly because folder 0 doesn't have the 0.0.png image, but if you find out, the labels.csv said that is on folder 8. But when I search there, it isn't there.

**Comment by mundher** [comment]
you may copy 0.0.png from any folder to folder 0. All folders contain the same images.

**Comment by AlejandraM97** [comment]
I have a question Mr, Mundher @mundher, do you have the "labels.csv" of folder 1? Is not on the link to download the dataset preprocessed

**Comment by mundher** [comment]
Here is a new link to the dataset with labels.csv" of folder 1
https://drive.google.com/file/d/19JMK_IeBFlEQAEt_nrWsJcHrdyHcZMhm/view?usp=sharing

**Comment by AlejandraM97** [comment]
Thank you so much Mr. Mundher!
